### ISSUE TITLE
I fought the chaos dragon but he keep regenerating health!

### ISSUE THREAD

**Issue by RandomSubscriberPlayer** [mikebald/SubServerExample#1]
The chaos dragon is immortal, what else can I add?!

**Comment by mikebald** [comment]
Don't worry, the Chaos Dragon is not immortal. However, there is a problem with Draconic Evolution where the health crystals atop the spires can regenerate and you can't see them until you relog. You can try relogging and see if that helps out; good luck.

If you want to read more about this, here's a link to the Draconic Evolution's issues that explains what's happening, https://github.com/brandon3055/Draconic-Evolution/issues/171  This issue also explains, from the mod author, why it's a bad idea to put Last Stand on Draconic Armor.
